# Problem set 3

In [1]:
import numpy as np
import numpy.random as npr

### Exercise 1

Write a Python function that accepts a list and checks if all elements are distinct.

#### Sample arguments and return values:

    Argument: [1, 2, 3, 4, 5]
    Returns: True
    
    Argument: [1, 2, 3, 2, 5]
    Returns: False

In [2]:
def is_unique(lst):
    return len(set(lst)) == len(lst)


print(is_unique([1, 2, 3, 4, 5]))
print(is_unique([1, 2, 3, 2, 5]))

True
False


### Exercise 2

1. Write (and test) a function that checks if 3 (an integer) is in a given list.
1. Write (and test) a function that returns the count of all 3s in a given list.
1. Write (and test) a function that checks if there are at least two consecutive elements both being 3.
1. Write (and test) a function that returns indexes of all 3s in a given list.
1. Write (and test) a function that returns a copy of a given list with all 3s replaced with 4.
1. Write (and test) a function that swaps the elements at indexes 3 and 4. (Assume that the list has at least 5 elements. You can choose if you want to do it in-place or return a new list.)

In [29]:
def is_3_in_list(lst: list):
    return 3 in lst


def count_3s(lst: list):
    return lst.count(3)


def consecutive_3s(lst: list):
    prev_element = 0
    for element in lst:
        if element and prev_element == 3:
            return True
        prev_element = element
    return False


def index_of_3s(lst: list):
    return [i for i, x in enumerate(lst) if x == 3]


def replace_3s_with_4s(lst: list):
    new_lst = []
    for element in lst:
        if element == 3:
            new_lst.append(4)
        else:
            new_lst.append(element)
    return new_lst


def swap_index_3_4(lst: list):
    lst[3], lst[4], = lst[4], lst[3]
    return lst


test_list = [1, 2, 3, 3, 4, 5, 4, 3, 2, 1, 0, 3, 23]
is_3_in_list(test_list)
count_3s(test_list)
consecutive_3s(test_list)
index_of_3s(test_list)
replace_3s_with_4s(test_list)
swap_index_3_4(test_list)


[1, 2, 3, 4, 3, 5, 4, 3, 2, 1, 0, 3, 23]

### Exercise 3

Implement the game of [Rock paper scissors](https://en.wikipedia.org/wiki/Rock_paper_scissors) in Python. Ask the user for the shapes selected by both players and then print out who the winner is (or if it is a tie). You can assume that the user enters valid shapes.

#### Sample executions:
    
    Player 1 [rock/paper/scissors]: rock
    Player 2 [rock/paper/scissors]: paper
    Player 2 has won.

    Player 1 [rock/paper/scissors]: scissors
    Player 2 [rock/paper/scissors]: paper
    Player 1 has won.

    Player 1 [rock/paper/scissors]: paper
    Player 2 [rock/paper/scissors]: paper
    It is a tie!

In [16]:
import numpy as np

GAME_RULES = {"rock": "scissors", "paper": "rock", "scissors": "paper"}


def play_game():
    while True:
        selection = input(f"Pick a shape [rock/paper/scissors] or (quit): ").lower()
        if selection == "quit":
            break

        opponent = np.random.choice(list(GAME_RULES))
        print(f"You picked {selection}, Opponent picked: {opponent}")
        if selection == opponent:
            print("It is a tie!")
        elif GAME_RULES[selection] == opponent:
            print("You won!")
        else:
            print("Your opponent won!")


play_game()


You picked rock, Opponent picked: rock
It is a tie!
You picked paper, Opponent picked: scissors
Your opponent won!
You picked scissors, Opponent picked: paper
You won!


### Exercise 4

Define the following 2-dimensional NumPy array:

$$ Y=\left[\begin{array}{ccc}
1 & 2 & 3\\
4 & 5 & 6\\
7 & 8 & 9
\end{array}\right] $$
         
- Print the shape and size of $Y$.
- Compute the rank of $Y$ (use online resources to learn what the rank is and what NumPy function or method to use).
- Compute the transpose of $Y$.
- Select the following sub-matrices of $Y$:

  $$ Y_1 = \left[\begin{array}{cc}
  1 & 2\\
  4 & 5
  \end{array}\right] $$
          
  $$ Y_2 =\left[\begin{array}{cc}
  5 & 6\\
  8 & 9
  \end{array}\right] $$

- Compute $Y_1 + Y_2$.
- Compute the matrix product $Y_1 Y_2$ and element-wise product $Y_1 \circ Y_2$ (also known as Hadamard product).

In [9]:
import numpy as np

y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(y.shape)
print(np.linalg.matrix_rank(y))
print(y.T)
y1 = y[:2, :2]
y2 = y[1:, 1:]

print(y1 @ y2)
print(y1 * y2)

(3, 3)
2
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[21 24]
 [60 69]]
[[ 5 12]
 [32 45]]


### Exercise 5

Recall Exercise 7 from the last set:

*Write a program that asks the user for floating-point numbers in a loop until the user enters "done", and then prints the maximum and minimum of these numbers.*

Update the program and store the numbers in a NumPy array. Instead of maximum and minimum, calculate the mean, the standard deviation, the 1st quartile, the median, and the 3rd quartile (hint: use `quantile` or `percentile` method).

Sample input and output:

    Enter a number: 6.1
    Enter a number: 2.7
    Enter a number: -9.5
    Enter a number: 3.4
    Enter a number: 5.8
    Enter a number: done
    Mean: 1.70
    Std. deviation: 5.75
    1st quartile: 2.70
    Median: 3.40
    3rd quartile: 5.80

In [10]:
temp = []

while True:
    text = input(f'Enter a number: ')
    if text.upper() == "DONE":
        break
    try:
        temp.append(float(text))
    except ValueError:
        print(f'{text} is not recognised as a valid input')

print(f'Mean: {np.mean(temp)}')
print(f'Std. deviation: {np.std(temp)}')
print(f'1st quartile: {np.quantile(temp, 0.25)}')
print(f'Median: {np.median(temp)}')
print(f'3rd quartile: {np.quantile(temp, 0.75)}')

 is not recognised as a valid input
Mean: 2491.266666666667
Std. deviation: 8489.30669698978
1st quartile: 18.0
Median: 54.0
3rd quartile: 494.0


### Exercise 6 (Sudoku)

Write a function that will check if a 9 x 9 grid with numbers (given as a NumPy array of integers) is a valid solution of classic [Sudoku](https://en.wikipedia.org/wiki/Sudoku), in other words, a function that checks if:

- each row contains all digits from 1 to 9,
- each column contains all digits from 1 to 9,
- each of the nine 3 x 3 blocks that compose the grid contains all digits from 1 to 9.

Hint:
- To check if all digits from 1 to 9 are in a NumPy sub-array `x`, you can use `sorted(x.flatten()) == [1, 2, 3, 4, 5, 6, 7, 8, 9]`.

Example of a valid Sudoku solution:
```
grid = np.array([[6, 5, 1, 2, 3, 8, 4, 9, 7],
                 [7, 9, 2, 1, 4, 5, 8, 6, 3],
                 [4, 3, 8, 6, 7, 9, 5, 2, 1],
                 [3, 8, 6, 5, 2, 7, 9, 1, 4],
                 [2, 1, 7, 4, 9, 3, 6, 8, 5],
                 [5, 4, 9, 8, 6, 1, 7, 3, 2],
                 [1, 7, 3, 9, 8, 4, 2, 5, 6],
                 [9, 2, 4, 3, 5, 6, 1, 7, 8],
                 [8, 6, 5, 7, 1, 2, 3, 4, 9]])
```
Find also examples that are not valid Sudoku solutions and check that your function returns `False`.

In [19]:
import numpy as np


def line_checker(grid):
    for row in grid:
        if sorted(row.flatten()) != [1, 2, 3, 4, 5, 6, 7, 8, 9]:
            return False
    return True


def sub_grid_checker(grid):
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            if sorted(grid[i:i + 3, j:j + 3].flatten()) != [1, 2, 3, 4, 5, 6, 7, 8, 9]:
                return False
    return True


def sudoku_checker(grid):
    status = [line_checker(grid), line_checker(grid.T), sub_grid_checker(grid)]
    if any(status):
        return "Valid"
    else:
        return "Invalid"


test_grid = np.array([[6, 5, 1, 2, 3, 8, 4, 9, 7],
                      [7, 9, 2, 1, 4, 5, 8, 6, 3],
                      [4, 3, 8, 6, 7, 9, 5, 2, 1],
                      [3, 8, 6, 5, 2, 7, 9, 1, 4],
                      [2, 1, 7, 4, 9, 3, 6, 8, 5],
                      [5, 4, 9, 8, 6, 1, 7, 3, 2],
                      [1, 7, 3, 9, 8, 4, 2, 5, 6],
                      [9, 2, 4, 3, 5, 6, 1, 7, 8],
                      [8, 6, 5, 7, 1, 2, 3, 4, 9]])

sudoku_checker(test_grid)


'Valid'

### Exercise 7 (Linear regression)

1. Prepare a data set which we will use for a linear regression analysis in step 2.

   - Generate a column vector $\mathbf{x} = \{x_i\}$ consisting of 8 samples $x_i$ drawn randomly from a uniform distribution between 0 and 10.
   - Generate a column vector $\mathbf{y} = \{y_i\}$, where $y_i = 20 + 2 x_i + \epsilon_i$, where $\epsilon_i$ denotes random noise drawn from a Gaussian distribution with zero mean and standard deviation 1.5.


2. Use the normal equation
   $$ \hat{\boldsymbol{\beta}} = \left(\mathrm{X}^{\mathsf{T}}\mathrm{X}\right)^{-1}\mathrm{X}^{\mathsf{T}}\mathbf{y} $$
   to estimate the coefficient vector $\boldsymbol{\beta}$ (with the intercept and the slope) of the least-squares line. In the equation, $\mathrm{X}$ denotes a matrix that consists of two columns: the elements in the first column are all ones, the second column is the vector $\mathbf{x}$.


In [39]:
X = np.array([[1, x] for x in np.random.uniform(0, 10, 8)])
y = 20 + 2 * X[:, 1] + np.random.normal(0, 1.5, 8)
b = np.linalg.inv(X.T @ X) @ X.T @ y
print(b)


[21.03434955  1.81119959]
